### ISSUE TITLE
Where are you?

### ISSUE THREAD

**Issue by nferhat** [Abdera7mane/Abdera7mane#1]

**Comment by Abdera7mane** [comment]
![image](https://github.com/Abdera7mane/Abdera7mane/assets/59313921/01c8972c-d140-4439-91c0-5e07b43c7755)

**Comment by nferhat** [comment]
Im sending this image to rainbolttwo and determine your exact position

**Comment by nferhat** [comment]
With all jokes aside, @Abdera7mane could you provide a way to contact you?

**Comment by Abdera7mane** [comment]
Soon:tm:

**Comment by nferhat** [comment]
> Soon™️

Ok sure.
If you want im available on signal/matrix, even irc, if that's your thing
